{{- $relName := .Release.Name -}}
{{- range $i, $e := until 10 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $relName }}-secret-{{ $i }}
  labels:
    app.kubernetes.io/instance: {{ $relName }}
type: Opaque
stringData:
  resource-index: "{{ $i }}"
  description: "Secret {{ $i }} for release {{ $relName }}"
---
{{- end }}
